spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:admin@cluster0.fy50f.mongodb.net/db?retryWrites=true&w=majority
goyelp:
  yelp:
    api-auth-token: to5syqyXXMYxBJ2up8Tv7WRZ7jpjJmfVX_3Pbt7Evnh4rdz2P0f8YaT6vP7A2dOW91UhXjKfjxRWl5dp57yECZg7UoUyH7WeyBeO7OoLJi_RkbojCAeN-wKoEaI9YXYx